---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
  "/v1/categories/{slug}":
    parameters:
    - name: slug
      in: path
      description: slug
      required: true
      schema:
        type: string
    get:
      summary: show category
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3400
