default: &default
  adapter: postgresql
  encoding: unicode
  url:  <%= ENV.fetch('DATABASE_URL') %>
  pool: <%= [ENV.fetch('SIDEKIQ_MAX_THREADS', 0).to_i, ENV.fetch('RAILS_MAX_THREADS', 0).to_i].max + 5 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  sslmode: require